DELETE http://localhost:8080/events/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQHRlc3QuY29tIiwiZXhwIjoxNzE5OTE2MTk3LCJ1c2VySUQiOjJ9.VpqcSk1SQVwjbqzlQ7w7nmws4cWkUKq5uPkYl5sG6H8
